version: '3.8'

services:
  db:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017/tcp'
    volumes:
      - db:/data/db
    environment:
      TZ: Asia/Tokyo
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  app:
    build: .
    image: ghcr.io/slashnephy/unveiler:master
    restart: always
    volumes:
      - data:/app/data
    depends_on:
      - db
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      MONGO_DATABASE_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017

volumes:
  db:
  data:
